### ISSUE TITLE
Not compatible with Mac OS X

### ISSUE THREAD

**Issue by GoogleCodeExporter** [aymanhs/jsyntaxpane#32]
```
What steps will reproduce the problem?
1. Standard Max OS X java installation.
2. Set an editor kit on a JEditorPane - i.e., pane.setEditorKit(new
JavaScriptSyntaxKit());

What is the expected output? What do you see instead?

Expect to see the text editor.  Instead I get the following error message:

Exception in thread "" java.lang.NoSuchMethodError:
java.util.Properties.stringPropertyNames()Ljava/util/Set;
    at jsyntaxpane.DefaultSyntaxKit.initKit(DefaultSyntaxKit.java:118)
    at jsyntaxpane.DefaultSyntaxKit.<clinit>(DefaultSyntaxKit.java:44)

What version of the product are you using? On what operating system?

0.9.1 on Mac OS X with Eclipse 3.4

Please provide any additional information below.

The method 'stringPropertyNames()' does not exist in Java SE 5.0.


```

Original issue reported on code.google.com by `greg.hedlund@gmail.com` on 22 Oct 2008 at 11:50

**Comment by GoogleCodeExporter** [comment]
```
Same results will be produced by doing jsyntaxpane.DefaultSyntaxKit.initKit();
```

Original comment by `greg.hedlund@gmail.com` on 22 Oct 2008 at 11:54

**Comment by GoogleCodeExporter** [comment]
```
Actually the problem is that I used JDK 6 and the method is not compatible with 
prior
versions.  
The code should work with JDK 1.6.
Is there a reason why you cannot use JDK 6?
```

Original comment by `ayman.al...@gmail.com` on 22 Oct 2008 at 1:18
- Changed state: **Accepted**

**Comment by GoogleCodeExporter** [comment]
Original comment by `ayman.al...@gmail.com` on 22 Oct 2008 at 1:18

**Comment by GoogleCodeExporter** [comment]
```
JDK 6 is not supported on Mac OS X (by default) yet.
```

Original comment by `greg.hedlund@gmail.com` on 22 Oct 2008 at 1:29

**Comment by GoogleCodeExporter** [comment]
```
Should have mentioned this before, I'm running OS X 10.5.5 with all updated 
installed.
```

Original comment by `greg.hedlund@gmail.com` on 22 Oct 2008 at 2:02

**Comment by GoogleCodeExporter** [comment]
```
Well, it's a JDK/JRE issue not Mac OS issue.  JSyntaxPane is only supported on 
JDK/JRE 6.
You can try and recompile on JDK 5.  You will probably need to re-implement a 
few
methods that are new in JDK 6.
If you can do that, and are willing to help, I can release the binary / source 
for a
5.0 compatible version.
```

Original comment by `ayman.al...@gmail.com` on 25 Oct 2008 at 1:53
- Changed state: **New**

**Comment by GoogleCodeExporter** [comment]
```
Well, it's a JDK/JRE issue not Mac OS issue.  JSyntaxPane is only supported on 
JDK/JRE 6.
You can try and recompile on JDK 5.  You will probably need to re-implement a 
few
methods that are new in JDK 6.
If you can do that, and are willing to help, I can release the binary / source 
for a
5.0 compatible version.
```

Original comment by `ayman.al...@gmail.com` on 25 Oct 2008 at 1:53

**Comment by GoogleCodeExporter** [comment]
```
Some pointers are there in
[http://code.google.com/p/jsyntaxpane/issues/detail?id=38]. Think we can close 
this
issue also with WONT FIX. The minimum requirement for JSyntaxPane can be raised 
to
Java 6.
```

Original comment by `subwiz` on 16 Nov 2008 at 9:31

**Comment by GoogleCodeExporter** [comment]
```
I agree.  CLosing as WOntFix, need JDK/JRE 1.6 as minimum requirement.
```

Original comment by `ayman.al...@gmail.com` on 16 Nov 2008 at 10:39
- Changed state: **WontFix**
